development:
  adapter: postgresql
  encoding: utf8
  database: nikomica
  pool: 5
  username: root
  password: 123456
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: dafobt4fipf70c
  host: dafobt4fipf70c.cll5ec2fc670.ap-northeast-1.rds.amazonaws.com
  username: ueoxbrwrilseln
  password: AF07k4KOd8iITzHAythrk7gucP
  port: 5432