development:
  adapter: postgresql
  encoding: utf8
  database: nikomica
  pool: 5
  username: root
  password: 123456
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: d80gjloc34gqn
  host: ec2-54-235-145-226.compute-1.amazonaws.com
  username: egrxnungaraolf
  password: qI1vIT7rc3ZuyH8achRk4S-IKw
  port: 5432