development:
  adapter: postgresql
  encoding: utf8
  database: nikomica
  pool: 5
  username: root
  password: 123456
  host: localhost


production:
  adapter: postgresql
  encoding: utf8
  database: df9ntcnip379cq
  host: ec2-54-83-36-90.compute-1.amazonaws.com
  username: xxnjhzoxpgqddu
  password: O47DpknoIMrOdQpkADrMOmYqbv
  port: 5432